// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxkuficrhpihhvbllkpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4a3VmaWNyaHBpaGh2Ymxsa3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDEwNDUsImV4cCI6MjA3MTExNzA0NX0.vT_puSPZRmTESgRGdK20XQx4PLy-Y6QS3UOpBbF1swo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});